#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
HOST_OS="x86_64-apple-darwin11.4.2"
CROSS_PREFIX=""

# zlib does not support in-tree builds, and so we copy the entire source
# directory to the build directory, and then build in place.
echo "Copying /projects/workrepo/xuggle-xuggler/captive/zlib/csrc to /projects/workrepo/xuggle-xuggler/captive/zlib/csrc"
# create the directory
mkdir -p "/projects/workrepo/xuggle-xuggler/captive/zlib/csrc"
# copy over all the source
cp -r "/projects/workrepo/xuggle-xuggler/captive/zlib/csrc/"* "/projects/workrepo/xuggle-xuggler/captive/zlib/csrc/"
# and make everything user writeable so distcheck will pass
chmod -R u+w "/projects/workrepo/xuggle-xuggler/captive/zlib/csrc/"*

# Check for 64 bit compiling
FLAG64=
case $HOST_OS in
  *64*)
    FLAG64="--64"
  ;;
esac

prefix="/usr/local"
exec_prefix="${prefix}"
libdir="${exec_prefix}/lib"
includedir="${prefix}/include"
mandir="${prefix}/share/man"
case $HOST_OS in
  *mingw*)
  # windows build requires special make instructions which will be done
  # from Makefile.am
  cp "/projects/workrepo/xuggle-xuggler/captive/zlib/csrc/win32/Makefile.gcc" "/projects/workrepo/xuggle-xuggler/captive/zlib/csrc/Makefile"
  ;;
  *)
  CHOST="x86_64-apple-darwin11.4.2" \
  CC="gcc" \
  CFLAGS="-fPIC -I/projects/workrepo/xuggle-xuggler/captive/stage${prefix}/include -arch x86_64 -g -O2" \
  LD="/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld" \
  LDFLAGS="-fPIC -L/projects/workrepo/xuggle-xuggler/captive/stage${exec_prefix}/lib -arch x86_64 " \
  CPP="gcc -E" \
  CPPFLAGS="" \
  CXX="g++" \
  CXXFLAGS="-arch x86_64 " \
  NM="/usr/bin/nm" \
  AS="as" \
  ASFLAGS="" \
  STRIP="strip" \
  RANLIB="ranlib" \
  AR="ar" \
  DLLTOOL="false" \
  prefix="${prefix}" \
  exec_prefix="${exec_prefix}" \
  libdir="${libdir}" \
  includedir="${includedir}" \
  mandir="${mandir}" \
  sh "/projects/workrepo/xuggle-xuggler/captive/zlib/csrc/configure" ${FLAG64} \
    --static \
    --prefix="${prefix}" || \
    (echo "Could not configure library: \"/projects/workrepo/xuggle-xuggler/captive/zlib\"; you may want to try disabling it or installing your own version" && exit 1)
  ;;
esac
