# Necessary to be in a file that is NOT processed by automake
VS_PKG_DEPENDENCIES=libavdevice libswscale libavfilter libavformat libavcodec libavutil
VS_PKG_LIBRARIES+=$(shell AR=$(AR) $(abs_top_srcdir)/mk/buildtools/find_archives.sh "../../../captive/stage${exec_prefix}/lib" $(VS_PKG_DEPENDENCIES) )
VS_PKG_LIBRARIES+=$(shell PKG_CONFIG_PATH="/projects/workrepo/xuggle-xuggler/captive/stage${exec_prefix}/lib/pkgconfig" pkg-config --static --libs-only-other $(VS_PKG_DEPENDENCIES) )

