#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
HOST_OS=x86_64-apple-darwin11.4.2

if [ "" = "1" ]; then
  CROSS="--host ${HOST_OS}"
else
  CROSS=
fi

CFLAGS="-I/projects/workrepo/xuggle-xuggler/captive/stage${prefix}/include -O0 -arch x86_64 -g -O2" 

case ${HOST_OS} in
  *darwin*)
  CFLAGS="-DHAVE_APPLE_OPENGL_FRAMEWORK ${CFLAGS}"
  ;;
esac

CC="gcc" \
CFLAGS="${CFLAGS}" \
LD="/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld" \
LDFLAGS="-L/projects/workrepo/xuggle-xuggler/captive/stage${exec_prefix}/lib -arch x86_64 " \
CPP="gcc -E" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="-arch x86_64 " \
NM="/usr/bin/nm" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/projects/workrepo/xuggle-xuggler/captive${exec_prefix}/bin@" sh /projects/workrepo/xuggle-xuggler/captive/libtiff/csrc/configure \
  ${CROSS} \
  --with-zlib-include-dir="/projects/workrepo/xuggle-xuggler/captive/stage${prefix}/include" \
  --with-zlib-lib-dir="/projects/workrepo/xuggle-xuggler/captive/stage${exec_prefix}/lib" \
  --with-pic \
  --disable-shared \
  --disable-dependency-tracking \
  --prefix="${prefix}" || \
  (echo "Could not configure library: \"/projects/workrepo/xuggle-xuggler/captive/libtiff\"; you may want to try disabling it or installing your own version" && exit 1)
