#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
X264_OPTIONS=
LDFLAGS="-arch x86_64 "
CFLAGS="-arch x86_64 -g -O2"
YASM=""
HOST_TYPE=Mac
HOST_OS=x86_64-apple-darwin11.4.2
VS_DEBUG=

if [ "" = "1" -o "${HOST_TYPE}" = "Mac" ]; then
  X264_OPTIONS="${X264_OPTIONS} --host=${HOST_OS} --cross-prefix="
fi

# Tell X264 about the captive libraries already built and fake
# installed

X264_OPTIONS="$X264_OPTIONS --enable-static"
X264_OPTIONS="$X264_OPTIONS --enable-pic"

if test "${HOST_TYPE}" = "Mac" ; then
  echo "Forcing debug build on Mac OS X due to text relocation in x264_cabac_encode_decision_asm; remove when x264 fixes that"
  VS_DEBUG=1 
fi
if test ! "x$VS_DEBUG" = "x"; then
  echo "Creating debug version of libx264: $VS_DEBUG"
  X264_OPTIONS="$X264_OPTIONS --disable-asm"
  X264_OPTIONS="$X264_OPTIONS --enable-debug"
else
  echo "Creating release version of libx264: $VS_DEBUG"
fi

if test "x$YASM" = "x"; then
# no assembly for us :(
  X264_OPTIONS="$X264_OPTIONS --disable-asm"
fi

# X264, despite claiming it, does not support in-tree builds,
# and so we copy the entire source
# directory to the build directory, and then build in place.
# copy over all the source
if [ ! -f "/projects/workrepo/xuggle-xuggler/captive/libx264/csrc/configure" ]; then
  echo "Copying /projects/workrepo/xuggle-xuggler/captive/libx264/csrc to /projects/workrepo/xuggle-xuggler/captive/libx264/csrc"
  # create the directory
  mkdir -p "/projects/workrepo/xuggle-xuggler/captive/libx264/csrc"
  # copy over all the source
  cp -r "/projects/workrepo/xuggle-xuggler/captive/libx264/csrc/"* "/projects/workrepo/xuggle-xuggler/captive/libx264/csrc/"
  # and make everything user writeable so distcheck will pass
  chmod -R u+w "/projects/workrepo/xuggle-xuggler/captive/libx264/csrc/"*
fi

echo "Configuring X264 with these options: $X264_OPTIONS"
CC="gcc" \
CFLAGS="-I/projects/workrepo/xuggle-xuggler/captive/stage${prefix}/include -arch x86_64 -g -O2" \
LD="/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld" \
LDFLAGS="-L/projects/workrepo/xuggle-xuggler/captive/stage${exec_prefix}/lib -arch x86_64 " \
CPP="gcc -E" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="-arch x86_64 " \
NM="/usr/bin/nm" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/projects/workrepo/xuggle-xuggler/captive${exec_prefix}/bin@" bash /projects/workrepo/xuggle-xuggler/captive/libx264/csrc/configure \
  --extra-cflags="$CFLAGS -I'/projects/workrepo/xuggle-xuggler/captive/stage${prefix}/include'" \
  --extra-ldflags="$LDFLAGS -L'/projects/workrepo/xuggle-xuggler/captive/stage${exec_prefix}/lib'" \
  --prefix="${prefix}" $X264_OPTIONS || \
  (echo "Could not configure library: \"/projects/workrepo/xuggle-xuggler/captive/libx264\"; you may want to try disabling it or installing your own version" && exit 1)
# for reasons I don't understand, on Mac this can end up being a link; nuke it
rm -f "/projects/workrepo/xuggle-xuggler/captive/libx264/csrc/Makefile"
cp -f "/projects/workrepo/xuggle-xuggler/captive/libx264/csrc/Makefile" "/projects/workrepo/xuggle-xuggler/captive/libx264/csrc/Makefile"
