#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
LIBRARY=libvo-aacenc
LIBRARY_OPTIONS=
HOST_TYPE=Mac
HOST_OS=x86_64-apple-darwin11.4.2

if [ "" = "1" ]; then
  CROSS="--host ${HOST_OS}"
else
  CROSS=
fi

# LIBRARY doesn't support VPATH builds, so we fake it
echo "Copying /projects/workrepo/xuggle-xuggler/captive/libvo-aacenc/csrc to /projects/workrepo/xuggle-xuggler/captive/libvo-aacenc/csrc"
# create the directory
mkdir -p /projects/workrepo/xuggle-xuggler/captive/libvo-aacenc/csrc
# copy over all the source
cp -r /projects/workrepo/xuggle-xuggler/captive/libvo-aacenc/csrc/* /projects/workrepo/xuggle-xuggler/captive/libvo-aacenc/csrc/
# and make everything user writeable so distcheck will pass
chmod -R u+w /projects/workrepo/xuggle-xuggler/captive/libvo-aacenc/csrc/*

echo "Configuring ${LIBRARY} with these options: $LIBRARY_OPTIONS"
CC="gcc" \
CFLAGS="-I/projects/workrepo/xuggle-xuggler/captive/stage${prefix}/include -arch x86_64 -g -O2" \
LD="/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld" \
LDFLAGS="-L/projects/workrepo/xuggle-xuggler/captive/stage${exec_prefix}/lib -arch x86_64 " \
CPP="gcc -E" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="-arch x86_64 " \
NM="/usr/bin/nm" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/projects/workrepo/xuggle-xuggler/captive${exec_prefix}/bin@" \
   sh /projects/workrepo/xuggle-xuggler/captive/libvo-aacenc/csrc/configure \
   --enable-silent-rules \
   --disable-dependency-tracking \
   --with-pic \
   --disable-shared \
   ${CROSS} \
  --prefix="${prefix}" $LIBRARY_OPTIONS || \
  (echo "Could not configure library: \"/projects/workrepo/xuggle-xuggler/captive/libvo-aacenc\"; you may want to try disabling it or installing your own version" && exit 1)
