#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
CPPFLAGS=""
LDFLAGS="-arch x86_64 "
CFLAGS="-arch x86_64 -g -O2"
HOST_TYPE=Mac
HOST_OS=x86_64-apple-darwin11.4.2

if [ "" = "1" ]; then
  CROSS="--host ${HOST_OS}"
else
  CROSS=
fi
VS_DEBUG=

if test ! "x$VS_DEBUG" = "x"; then
  CFLAGS="-DLIBSPANDSP_EXPORTS=1 -g -O0 -arch x86_64 -g -O2"
  echo "Creating debug version of spandsp: ${VS_DEBUG}; ${CFLAGS}"
else
  CFLAGS="-DLIBSPANDSP_EXPORTS=1 -g -O2 -arch x86_64 -g -O2"
  echo "Creating release version of spandsp: ${VS_DEBUG}; ${CFLAGS}"
fi
export ac_cv_func_malloc_0_nonnull=yes
export ac_cv_func_realloc_0_nonnull=yes
LDFLAGS="-L/projects/workrepo/xuggle-xuggler/captive/stage${exec_prefix}/lib -arch x86_64 " 
LIBS=-lz
case ${HOST_OS} in
  *mingw*|*cygwin*)
  LIBS="-lws2_32 -lmingw32 -lmingwex ${LIBS}"
  ;;
esac
export LIBS

LIBS="${LIBS}" \
CC="gcc" \
CFLAGS="-I/projects/workrepo/xuggle-xuggler/captive/stage${prefix}/include $CFLAGS" \
LD="/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld" \
LDFLAGS="${LDFLAGS}"
CPP="gcc -E" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="-arch x86_64 " \
NM="/usr/bin/nm" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/projects/workrepo/xuggle-xuggler/captive${exec_prefix}/bin@" sh /projects/workrepo/xuggle-xuggler/captive/spandsp/csrc/configure \
  ${CROSS} \
  --disable-shared \
  --with-pic \
  --prefix="${prefix}" || \
  (echo "Could not configure library: \"/projects/workrepo/xuggle-xuggler/captive/spandsp\"; you may want to try disabling it or installing your own version" && exit 1)
