#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
HOST_TYPE=Mac
HOST_OS=x86_64-apple-darwin11.4.2
HOST_CPU=x86_64
HOST_VENDOR=apple
HOST_OS_C=darwin11.4.2

VS_DEBUG=

CAPTIVE_ENABLE_FFMPEG_GPL=yes

FFMPEG_OPTIONS=
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --extra-version=xuggle-5.5"

# Tell FFMPEG about the captive libraries already built and fake
# installed
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --extra-cflags=-I/projects/workrepo/xuggle-xuggler/captive/stage${prefix}/include"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --extra-ldflags=-L/projects/workrepo/xuggle-xuggler/captive/stage${exec_prefix}/lib"
# Set up a place where pkg-config looks for installed packages
export PKG_CONFIG_PATH="/projects/workrepo/xuggle-xuggler/captive/stage${exec_prefix}/lib/pkgconfig"

FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-shared"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-pic"
#FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-runtime-cpudetect"

if test "x$CAPTIVE_ENABLE_FFMPEG_GPL" = "xyes"; then
  FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-gpl --enable-nonfree"
  # x264 can only be used in GPL mode
  FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libx264"
fi
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-version3"

case $HOST_OS in
  *darwin*)
    # GNU Configure sometimes adds darwin version numbers; this strips them
    HOST_OS_C=darwin
    # Sigh; but on Xcode 4.2 there is a compiler bug with register allocation.  
    # Rather than expensively detect the compiler version, I'm going to hard-code
    # darwin builds for now to debug (no assembly) and wait for a compiler or ffmpeg
    # fix
    VS_DEBUG=1
  ;;
esac
if [ "" = "1" ]; then
  FFMPEG_OPTIONS="${FFMPEG_OPTIONS} --enable-cross-compile --cross-prefix= --arch=${HOST_CPU} --target-os=${HOST_OS_C}"
  # Override the cross setting for PKG-CONFIG since that is not usually set up to
  # be cross-compile friendly
  if ! "pkg-config" --version > /dev/null 2>&1; then
    # default to pkg-config WITHOUT a prefix; we don't really care since
    # we're faking out pkg-config anyway
    FFMPEG_OPTIONS="$FFMPEG_OPTIONS --pkg-config=pkg-config"
  fi
fi

if test ! "x$VS_DEBUG" = "x"; then
  FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-stripping"
  FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-asm"
  FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-optimizations"
  FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-mmx"
  FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-mmx2"
fi
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libmp3lame"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libvorbis"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libtheora"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libspeex"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libvo-aacenc"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libopencore-amrnb --enable-libopencore-amrwb"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-librtmp"
case $HOST_OS in
  *mingw*|*cygwin*)
   # ffmpeg configure doesn't handle pkg-config files correctly when
   # static linking, so we fix librtmp here.
   FFMPEG_OPTIONS="$FFMPEG_OPTIONS --extra-libs=-lwinmm"
  ;;
esac
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-openssl"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-zlib"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libvpx"

echo "Configuring FFMPEG with these options: $FFMPEG_OPTIONS"
cd /projects/workrepo/xuggle-xuggler/captive/ffmpeg/csrc
CC="gcc" \
LD="/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld" \
CPP="gcc -E" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="-arch x86_64 " \
NM="/usr/bin/nm" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/projects/workrepo/xuggle-xuggler/captive${exec_prefix}/bin@" sh /projects/workrepo/xuggle-xuggler/captive/ffmpeg/csrc/configure \
  --prefix="${prefix}" $FFMPEG_OPTIONS || \
  (echo "Could not configure library: \"/projects/workrepo/xuggle-xuggler/captive/ffmpeg\"; you may want to try disabling it or installing your own version" && exit 1)
# Attempt to stop unnecessary re-configs by touching this
MAKEFILE="/projects/workrepo/xuggle-xuggler/captive/ffmpeg/csrc/Makefile"
if [ -f "${MAKEFILE}" ]; then
  echo "Updating ${MAKEFILE} to stop unnecessary builds"
  touch "${MAKEFILE}"
fi
